version: '3.1'

services:

  wordpress:
    image: wordpress
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_HOST: 10.7.14.22
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD:
      WORDPRESS_DB_NAME: pan_african_blog
